[package]
name = "FundVerse_backend"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
ic-cdk = "0.14"
ic-cdk-macros = "0.14"
candid = "0.10"
ic-stable-structures = "0.6.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
